#!/usr/bin/env python3
import psutil
import argparse


def get_cpu_metrics():
    cpu_times = psutil.cpu_times()
    return f'''  system.cpu.idle {cpu_times.idle}
  system.cpu.user {cpu_times.user}
  system.cpu.guest {cpu_times.guest}
  system.cpu.iowait {cpu_times.iowait}
  system.cpu.stolen {cpu_times.steal}
  system.cpu.system {cpu_times.system}'''


def get_mem_metrics():
    vmem_usage = psutil.virtual_memory()
    swap_usage = psutil.swap_memory()
    return f'''  virtual total {vmem_usage.total}
  virtual used {vmem_usage.used}
  virtual free {vmem_usage.free}
  virtual shared {vmem_usage.shared}
  swap total {swap_usage.total}
  swap used {swap_usage.used}
  swap free {swap_usage.free}'''


def main():
    parser = argparse.ArgumentParser(
        description='Prints system metrics.')
    parser.add_argument('resource', choices=[
                        'cpu', 'mem'], help="Choose the resource")
    args = parser.parse_args()
    if args.resource == 'cpu':
        print(get_cpu_metrics())
    elif args.resource == 'mem':
        print(get_mem_metrics())


if __name__ == "__main__":
    main()
